FantasyRollerDerby/Models/_Home.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Data;

namespace FantasyRollerDerby.Models
{
    public class _Home
    {
        //All the classes for the home page feed into this class
        //All the lists needed for the home page are held here
        //Any methods specific to the home page are located here

        #region CLASSES
        public User cUser { get; set; }
        public League cLeague { get; set; }
        public FantasyTeam cFantasyTeam { get; set; }
        #endregion

        #region LISTS
        public List<League> list_cLeaguePublic { get; set; }
        public List<League> list_cLeaguePrivate { get; set; }
        public List<FantasyTeam> list_cFantasyTeam { get; set; }
        #endregion

        #region METHODS
        public Return GetLeagueMemberData(SqlConnection dbconAPP, _Home model)
        {
            Return cR = new Return();

            model.cLeague = new League();
            model.list_cLeaguePublic = new List<League>();
            model.list_cLeaguePrivate = new List<League>();
            model.list_cLeaguePublic = model.cLeague.GetLeagueList(dbconAPP, model.cLeague, true, model.cUser.UserID);
            model.list_cLeaguePrivate = model.cLeague.GetLeagueList(dbconAPP, model.cLeague, false, model.cUser.UserID);

            cR.ReturnFlag = true;
            return cR;
        }

        public Return GetNonLeagueMemberData(SqlConnection dbconAPP, _Home model)
        {
            Return cR = new Return();

            model.cLeague = new League();
            model.list_cLeaguePublic = new List<League>();
            model.list_cLeaguePrivate = new List<League>();
            model.list_cLeaguePublic = model.cLeague.GetLeagueList(dbconAPP, model.cLeague, true);
            model.list_cLeaguePrivate = model.cLeague.GetLeagueList(dbconAPP, model.cLeague, false);

            cR.ReturnFlag = true;
            return cR;
        }
        #endregion
    }
}

FantasyRollerDerby/Controllers/LeagueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FantasyRollerDerby.Models;
using System.Data.SqlClient;
using System.Configuration;
using System.Data;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.IO;

namespace FantasyRollerDerby.Controllers
{
    public class LeagueController : Controller
    {
        #region dbKahn
        //SQL Connection
        SqlConnection dbconAPP;
        public SqlConnection GetConnection(string conType = "WebApp")
        {
            switch (conType.ToUpper())
            {
                case "WEBAPP":
                    return new SqlConnection(ConfigurationManager.ConnectionStrings["JND_FantasyRollerDerby"].ConnectionString.ToString());
                default:
                    return new SqlConnection(ConfigurationManager.ConnectionStrings["JND_FantasyRollerDerby"].ConnectionString.ToString());
            }
        }
        #endregion

        #region GETS
        [Authorize]
        public ActionResult Index(string leagueType, string leagueID, int seasonID, int fantasyTeamID, string errMsg = "")
        {
            _League model = new _League();
            model.cLeague = new League();
            model.list_cLeague = new List<League>();
            model.cSeason = new Season();
            model.list_cFantasyTeam = new List<FantasyTeam>();
            model.cFantasyTeam = new FantasyTeam();
            model.list_LeagueStanding = new List<FantasyTeam>();
            model.cSkater = new Skater();
            model.list_Skater = new List<Skater>();

            try
            {
                //setup errMsg
                if(errMsg != "")
                {
                    ViewBag.LeagueError = errMsg;
                }

                //Get connection
                dbconAPP = GetConnection();
                dbconAPP.Open();

                //Get user info
                model.cUser = new User();
                ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext()
                    .GetUserManager<ApplicationUserManager>()
                    .FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
                model.cUser.AspNetUserID = user.Id;
                model.cUser.UserID = model.cUser.GetUserID(dbconAPP, model.cUser.AspNetUserID);
                model.cUser.FullName = model.cUser.GetUserName(dbconAPP, model.cUser.UserID);
                if(model.cUser.FullName == "Jason Deutsch")
                {
                    ViewBag.Creator = true;
                }

                //Get League info
                model.cLeague = model.cLeague.GetLeagueInfo(dbconAPP, Convert.ToInt32(leagueID), seasonID);
                model.cFantasyTeam = new FantasyTeam();
                model.cFantasyTeam.Name = model.cLeague.TeamName;
                model.cFantasyTeam.FantasyTeamID = fantasyTeamID;

                //Enable or disable the commish edit league button
                if(model.cLeague.CommissionerUserID == model.cUser.UserID)
                {
                    ViewBag.IsCommish = true;
                }

                ////Enable or disable the draft room button based on when the draft time is
                //int beforeDraft = (30 * 60) * -1; //allowed into the draft 30 minutes before
                //int afterDraft = (model.cLeague.DraftTimePerTeam * model.cLeague.RosterSize * model.cLeague.MaxTeams) + (15 * 60); //allowed into draft 15 minutes after the end of the draft
                //var test1 = model.cLeague.DraftDate.ToFileTimeUtc();
                //var test2 = model.cLeague.DraftDate.ToBinary();
                //var test3 = model.cLeague.DraftDate.ToUniversalTime();
                //var test4 = model.cLeague.DraftDate.ToFileTime();
                //var testNow = DateTime.Now.ToBinary();
                //var testNowUTC = DateTime.UtcNow;
                //var testNowUtcBinary = DateTime.UtcNow.ToBinary();
                //var testNowFileTimeUTC = DateTime.Now.ToFileTimeUtc();
                //var testNowFileTime = DateTime.Now.ToFileTime();

                //var inactiveDraftTime = model.cLeague.DraftDate.AddSeconds(afterDraft).ToFileTime();
                //var activeDraftTime = model.cLeague.DraftDate.AddSeconds(beforeDraft).ToFileTime();
                //var currentTime = DateTime.Now.ToFileTime();
                ////Having trouble getting this date comparison to work on Azure web hosting solutions
                ////double intInactiveDate = Convert.ToDouble(inactiveDraftTime.ToString("yyyyMMddhhmmss"));
                ////double intActiveDate = Convert.ToDouble(activeDraftTime.ToString("yyyyMMddhhmmss"));
                ////double intDateTimeNow = Convert.ToDouble(DateTime.Now.ToString("yyyyMMddhhmmss"));
                ////Azure web hosting service compares to the tick so this won't work 
                //if (inactiveDraftTime > currentTime && activeDraftTime < currentTime)
                //{
                //    //Enable the draft button
                //    ViewBag.IsDraft = true;
                //}
                ////ViewBag.IsDraft = true;

                //get list of teams first by total team points, then by draft pick number
                model.cSeason = new Season();
                model.list_cFantasyTeam = new List<FantasyTeam>();
                model.list_cFantasyTeam = model.cFantasyTeam.GetFantasyTeamStandings(dbconAPP, model.cLeague.SeasonID, model.cLeague.LeagueID);

                //if list is empty then sort teams by draft order
                model.list_SeasonFantasyTeams = model.cFantasyTeam.GetSeasonFantasyTeamList(dbconAPP, model.cLeague.SeasonID);
                if (model.list_cFantasyTeam.Count < 1)
                {
                    //Get season draft order
                    model.cSeason.SeasonID = model.cLeague.SeasonID;
                    model.cSeason.GetSeasonInfo(dbconAPP, model.cSeason);

                    if(model.cSeason.DraftOrder != "")
                    {
                        //Order teams according to the draft order
                        foreach (var item in model.cSeason.DraftOrder.Split('|'))
                        {
                            FantasyTeam tempFT = new FantasyTeam();
                            tempFT = model.list_SeasonFantasyTeams.Find(x => x.FantasyTeamID == Convert.ToInt32(item));
                            model.list_cFantasyTeam.Add(tempFT);
                        }
                    }
                    else
                    {
                        model.list_cFantasyTeam = model.list_SeasonFantasyTeams;
                    }
                }

                //Create standings list
                //First, verify that all teams are included in the standings list
                model.list_LeagueStanding = new List<FantasyTeam>();
                if (model.list_cFantasyTeam.Count != model.list_SeasonFantasyTeams.Count)
                {
                    model.list_LeagueStanding = model.list_cFantasyTeam.OrderByDescending(x => x.TotalTeamPoints).ToList();
                    foreach (var item in model.list_SeasonFantasyTeams)
                    {
                        var test = model.list_LeagueStanding.Find(m => m.FantasyTeamID == item.FantasyTeamID);
                        if (test == null)
                        {
                            item.TotalTeamPoints = 0.00;
                            model.list_LeagueStanding.Add(item);
                        }
                    }
                }
                else
                {
                    model.list_LeagueStanding = model.list_cFantasyTeam.OrderByDescending(x => x.TotalTeamPoints).ToList();
                }

                //set fantasy team id and get fantasy team info
                model.cFantasyTeam.FantasyTeamID = fantasyTeamID;
                model.cFantasyTeam.GetFantasyTeamInfo(dbconAPP, model.cFantasyTeam);

                //Get Fantasy Team skater list
                model.cSkater = new Skater();
                model.list_Skater = new List<Skater>();
                model.list_Skater = model.cSkater.GetFantasyTeamSkaterList(dbconAPP, seasonID, fantasyTeamID);

                //Determine if the season is over
                if(DateTime.Now > model.cLeague.EndDate)
                {
                    ViewBag.SeasonEnded = true;
                    //need to change so users can't select a start date before the draft date, etc.
                    ViewBag.MinDate = DateTime.Now.ToString("yyyy-MM-dd");
                    ViewBag.MaxDate = DateTime.Now.AddYears(10).ToString("yyyy-MM-dd");
                }
            }
            catch (Exception ex)
            {
                ViewBag.LeagueError += "ERROR: " + ex.Message + " (League.Index[GET]).";
                return View(model);
            }
            finally
            {
                if (dbconAPP != null && dbconAPP.State == System.Data.ConnectionState.Open)
                {
                    dbconAPP.Close();
                }
            }
            //string fantasyTeamName, string leagueName, int seasonID, int teamID
            Session["fantasyTeamName"] = model.cFantasyTeam.Name;
            Session["leagueName"] = model.cLeague.LeagueName;
            Session["seasonID"] = model.cLeague.SeasonID;
            Session["teamID"] = model.cFantasyTeam.FantasyTeamID;
            return View(model);
        }

        // GET: League/Create
        [Authorize]
        public ActionResult CreateLeague(string leagueType, string errMsg)
        {
            _League model = new _League();
            try
            {
                //Set errMsg
                ViewBag.LeagueError = errMsg;

                //Get connection
                dbconAPP = GetConnection();
                dbconAPP.Open();

                //Get user info
                model.cUser = new User();

FantasyRollerDerby/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

FantasyRollerDerby/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<br /><img src="~/Images/Contact.png" class="img-responsive" /><br />

<h1 class="text-center">Got Questions?</h1>
<h1 class="text-center">Got ideas for cool features to add to this site?</h1>
<h1 class="text-center">Bored and want a pen pal?</h1>
<h1 class="text-center">Send us an email :)</h1>

<address class="text-center">
    <strong>Support:</strong>   <a href="mailto:Support@example.com" class="linkBlue">Support@GoodLandFRD.com</a><br />
</address>

FantasyRollerDerby/Views/Home/GoToLeague.cshtml
@model FantasyRollerDerby.Models.League

@{
    ViewBag.Title = "GoToLeague";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GoToLeague</h2>

<div>
    <h4>League</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CommissionerUserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CommissionerUserID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FantasyTeamID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FantasyTeamID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CommissionerUserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CommissionerUserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TeamName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeamName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Slogan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Slogan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LeagueName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeagueName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SeasonID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SeasonID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxTeams)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxTeams)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Teams)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Teams)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DraftDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DraftDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateByUserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateByUserID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RetireByUserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RetireByUserID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RetireDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RetireDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isPublic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isPublic)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.LeagueID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FantasyRollerDerby/Views/Home/Member.cshtml
@model FantasyRollerDerby.Models._Home

@{
    ViewBag.Title = "Home Page";
}

<script type="text/javascript">
    $(document).ready(function () {
        if (('@ViewBag.HomeError') != "") {
            //unhide modal
            $("#modalHomeError").removeClass("hidden");
            $("#triggerHomeError").click();
        } else {
            //hide modal or keep it hidden
            $("#modalHomeError").addClass("hidden");
        }
    });

    function GoToLeague(LeagueID, SeasonID, FantasyTeamID, type){
        $("#inputLeagueID").val(LeagueID);
        $("#inputSeasonID").val(SeasonID);
        $("#inputFantasyTeamID").val(FantasyTeamID);
        $("#inputBtnAction").val(type);
        $("#hiddenSubmit").click();
    }
</script>

<!--Error Modal-->
<button id="triggerHomeError" data-toggle="modal" class="hidden" data-target="#modalHomeError"></button>
<div id="modalHomeError" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title text-center"><b>Home Page Error</b></h2>
            </div>
            <div class="modal-body">
                <div class="danger row">
                    <h4 class="text-center">@ViewBag.HomeError</h4>
                </div>
            </div>
            <div class="modal-footer">
                <h6 class="text-center">***click outside this window to close the notification***<br /></h6>
            </div>
        </div>
    </div>
</div>
<!--Error Modal-->

<!--v CoverFlow v-->
@*<div style="background-color:black;">
    <div class="row">
        <div class="col-xs-12">
            @Html.Partial("_CoverFlow")
        </div>
    </div>
</div>*@
<!--^ CoverFlow ^-->

@using (Html.BeginForm("Index", "League", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <!--v Input Items v-->
    <input id="inputLeagueID" type="hidden" name="LeagueID" value="none" />
    <input id="inputSeasonID" type="hidden" name="SeasonID" value="none" />
    <input id="inputFantasyTeamID" type="hidden" name="FantasyTeamID" value="none" />
    <input id="inputBtnAction" type="hidden" name="buttonAction" value="none" />
    <input id="hiddenSubmit" type="submit" class="hidden" />
    <!--^ Input Items ^-->

    <!--v Welcome Message v-->
    <div class="row mobileHide">
        <video class="logoGreeting" autoplay loop>
            <source src="http://jasondeutsch.info/Images/Header_Video.mp4" type="video/mp4">
            Your browser does not support the video tag.
        </video>
    </div>
    <div class="row">
        <img src="~/Images/Member_header.jpg" class="logoGreeting" />
    </div>
    <!--^ Welcome Message ^-->
    
    <!--v Public Leagues v-->
    <div class="row">
        <br /><br /><br />
        <img src="~/Images/YourPublicLeagues.png" class="img-responsive" />
        <br />
        <div id="divPublicLeaguesSearchGrid mobileText">
            @if (Model.list_cLeaguePublic != null && Model.list_cLeaguePublic.Count > 0)
            {
                WebGrid gridPublicLeagues = new WebGrid(Model.list_cLeaguePublic, rowsPerPage: 5,
                    sortFieldName: "gridPublicLeaguesSort", ajaxUpdateContainerId: "divPublicLeaguesSearchGrid");
                var rowNum = 0;
                @gridPublicLeagues.GetHtml(tableStyle: "table table-bordered table-striped table-hover tableHome gridPublicLeagues table-responsive",
             htmlAttributes: new { id = "gridPublicLeagues" },
             headerStyle: "",
             footerStyle: "",
             alternatingRowStyle: "",
             columns: gridPublicLeagues.Columns(
                 gridPublicLeagues.Column("Logo", header: " ",
                     format:
                    @<div>
                        <img class="img-responsive memberListLogo mobileHide" src="~/Images/TeamLogos/@item.Logo" />
                        @Html.Hidden("RowNumber", rowNum = rowNum + 1)
                        @Html.Hidden("list_cLeaguePublic[" + (rowNum - 1) + "].FantasyTeamID", (int)item.FantasyTeamID)
                        @Html.Hidden("list_cLeaguePublic[" + (rowNum - 1) + "].TeamName", (string)item.TeamName)
                        @Html.Hidden("list_cLeaguePublic[" + (rowNum - 1) + "].LeagueID", (int)item.LeagueID)
                        @Html.Hidden("list_cLeaguePublic[" + (rowNum - 1) + "].SeasonID", (int)item.SeasonID)
                        @Html.Hidden("list_cLeaguePublic[" + (rowNum - 1) + "].CommissionerUserID", (int)item.CommissionerUserID)
                        @Html.Hidden("list_cLeaguePublic[" + (rowNum - 1) + "].CommissionerUserName", (string)item.CommissionerUserName)
                        @Html.Hidden("list_cLeaguePublic[" + (rowNum - 1) + "].LeagueName", (string)item.LeagueName)
                        @Html.Hidden("list_cLeaguePublic[" + (rowNum - 1) + "].DraftDate", (DateTime)item.DraftDate)
                        @Html.Hidden("list_cLeaguePublic[" + (rowNum - 1) + "].StartDate", (DateTime)item.StartDate)
                        @Html.Hidden("list_cLeaguePublic[" + (rowNum - 1) + "].EndDate", (DateTime)item.EndDate)
                        @Html.Hidden("list_cLeaguePublic[" + (rowNum - 1) + "].isPublic", (Boolean)item.isPublic)
                    </div>
                    ),
                gridPublicLeagues.Column("TeamName", header: "Team Name", format: (item) => item.TeamName),
                gridPublicLeagues.Column("LeagueName", header: "League Name",
                    format: @<button class="btn btn-link" onclick="GoToLeague('@item.LeagueID', '@item.SeasonID', '@item.FantasyTeamID', 'public');">@item.LeagueName</button>),
                gridPublicLeagues.Column("Commissioner", header: "Commissioner", format: (item) => item.CommissionerUserName),
                gridPublicLeagues.Column("DraftDate", header: "Draft Date", format: (item) => string.Format("{0:MM/dd/yyyy}", item.DraftDate)),
                gridPublicLeagues.Column("StartDate", header: "Start Date", format: (item) => string.Format("{0:MM/dd/yyyy}", item.StartDate)),
                gridPublicLeagues.Column("EndDate", header: "End Date", format: (item) => string.Format("{0:MM/dd/yyyy}", item.EndDate))))
            }
            else
            {
                <table id="gridPublicLeagues" class="table table-bordered table-striped table-hover tableHome table-responsive">
                    <thead>
                        <tr class="text-center">
                            <th scope="col" class="text-center"></th>
                            <th scope="col" class="text-center">Team Name</th>
                            <th scope="col" class="text-center">League Name</th>
                            <th scope="col" class="text-center">Commissioner</th>
                            <th scope="col" class="text-center">Draft Date</th>
                            <th scope="col" class="text-center">Start Date</th>
                            <th scope="col" class="text-center">End Date</th>
                        </tr>
                    </thead>
                </table>
                <h3 class="text-center">No Results</h3>
            }
        </div>
        @Html.ActionLink(linkText: "Create League", actionName: "CreateLeague", controllerName: "League",
            routeValues: new { leagueType = "public" }, htmlAttributes: new { @class = "btn btn-primary pull-right" })
    </div>
    <!--^ Public Leagues ^-->
    <br /><br />
    <!--v Private Leagues v-->
    <div class="row">
        <img src="~/Images/YourPrivateLeagues.png" class="img-responsive" />
        <br />
        <div id="divPrivateLeaguesSearchGrid mobileText">
            @if (Model.list_cLeaguePrivate != null && Model.list_cLeaguePrivate.Count > 0)
            {
                WebGrid gridPrivateLeagues = new WebGrid(Model.list_cLeaguePrivate, rowsPerPage: 5,
                    sortFieldName: "gridPrivateLeaguesSort", ajaxUpdateContainerId: "divPrivateLeaguesSearchGrid");
                var rowNum = 0;
                @gridPrivateLeagues.GetHtml(tableStyle: "table table-bordered table-striped table-hover tableHome gridPrivateLeagues table-responsive",
                htmlAttributes: new { id = "gridPrivateLeagues" },
                headerStyle: "",
                footerStyle: "",
                alternatingRowStyle: "",
                columns: gridPrivateLeagues.Columns(
                 gridPrivateLeagues.Column("Logo", header: " ",
                     format:
                    @<div>
                        <img class="img-responsive memberListLogo mobileHide" src="~/Images/TeamLogos/@item.Logo" />
                        @Html.Hidden("RowNumber", rowNum = rowNum + 1)
                        @Html.Hidden("list_cLeaguePrivate[" + (rowNum - 1) + "].FantasyTeamID", (int)item.FantasyTeamID)
                        @Html.Hidden("list_cLeaguePrivate[" + (rowNum - 1) + "].TeamName", (string)item.TeamName)
                        @Html.Hidden("list_cLeaguePrivate[" + (rowNum - 1) + "].LeagueID", (int)item.LeagueID)
                        @Html.Hidden("list_cLeaguePrivate[" + (rowNum - 1) + "].SeasonID", (int)item.SeasonID)
                        @Html.Hidden("list_cLeaguePrivate[" + (rowNum - 1) + "].CommissionerUserID", (int)item.CommissionerUserID)
                        @Html.Hidden("list_cLeaguePrivate[" + (rowNum - 1) + "].CommissionerUserName", (string)item.CommissionerUserName)
                        @Html.Hidden("list_cLeaguePrivate[" + (rowNum - 1) + "].LeagueName", (string)item.LeagueName)
                        @Html.Hidden("list_cLeaguePrivate[" + (rowNum - 1) + "].DraftDate", (DateTime)item.DraftDate)
                        @Html.Hidden("list_cLeaguePrivate[" + (rowNum - 1) + "].StartDate", (DateTime)item.StartDate)
                        @Html.Hidden("list_cLeaguePrivate[" + (rowNum - 1) + "].EndDate", (DateTime)item.EndDate)
                        @Html.Hidden("list_cLeaguePrivate[" + (rowNum - 1) + "].isPublic", (Boolean)item.isPublic)
                    </div>
                    ),
                gridPrivateLeagues.Column("TeamName", header: "Team Name", format: (item) => item.TeamName),
                gridPrivateLeagues.Column("LeagueName", header: "League Name", 
                    format: @<button class="btn btn-link" onclick="GoToLeague('@item.LeagueID', '@item.SeasonID', '@item.FantasyTeamID', 'private');">@item.LeagueName</button>),
                gridPrivateLeagues.Column("Commissioner", header: "Commissioner", format: (item) => item.CommissionerUserName),
                gridPrivateLeagues.Column("DraftDate", header: "Draft Date", format: (item) => string.Format("{0:MM/dd/yyyy}", item.DraftDate)),
                gridPrivateLeagues.Column("StartDate", header: "Start Date", format: (item) => string.Format("{0:MM/dd/yyyy}", item.StartDate)),
                gridPrivateLeagues.Column("EndDate", header: "End Date", format: (item) => string.Format("{0:MM/dd/yyyy}", item.EndDate))))
            }
            else
            {
                <table id="gridPrivateLeagues" class="table table-bordered table-striped table-hover tableHome table-responsive">
                    <thead>
                        <tr class="text-center">
                            <th scope="col" class="text-center"></th>
                            <th scope="col" class="text-center">Team Name</th>
                            <th scope="col" class="text-center">League Name</th>
                            <th scope="col" class="text-center">Commissioner</th>
                            <th scope="col" class="text-center">Draft Date</th>
                            <th scope="col" class="text-center">Start Date</th>
                            <th scope="col" class="text-center">End Date</th>
                        </tr>
                    </thead>
                </table>
                <h3 class="text-center">No Results</h3>
            }
        </div>
        @Html.ActionLink(linkText: "Create League", actionName: "CreateLeague", controllerName: "League",
            routeValues: new { leagueType = "private" }, htmlAttributes: new { @class = "btn btn-primary pull-right" })
    </div>
    <!--^ Private Leagues ^-->
}

FantasyRollerDerby/Views/Home/_JoinLeague.cshtml
<!--Error-->
<div id="JoinLeagueError" class="row hidden alert alert-danger">
    <h4>@ViewBag.JoinLeagueError</h4>
</div>
<!--Error-->

@using (Html.BeginForm("CreateTeam", "League", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div id="divJoinLeaguePartial" class="row">
        <div class="col-md-3">
            <h4>Team Name: </h4>
        </div>
        <div class="col-md-8">
            <input name="FantasyTeamName" type="text" class="form-control" required />
        </div>
        <div class="col-md-1"></div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-3">
            <h4>Team Slogan: </h4>
        </div>
        <div class="col-md-8">
            <input name="FantasyTeamSlogan" type="text" class="form-control" />
        </div>
        <div class="col-md-1"></div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-3">
            <h4>Team Logo: </h4>
        </div>
        <div class="col-md-4">
            <input type="file" name="FantasyTeamLogo" />
        </div>
        <div class="col-md-5"></div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <input type="submit" id="btnCreateTeam" value="Create Team" 
                    class="btn btn-primary" style="width:100%;" />
        </div>
        <div class="col-md-4"></div>
    </div>
    
    <input type="hidden" name="FantasyTeamUserID" value="@Model.UserID" />
    <input type="hidden" name="FantasyTeamLeagueID" value="@Model.LeagueID" />
}